#!/bin/sh

cd frontend || exit 1
npm run build:acc || exit 1
npm run prettier:check || exit 1

cd ../backend || exit 1
npm run build || exit 1

cd ../KnowledgeBase/KnowledgeBaseBNB || exit 1
./build.sh || exit 1

exit $?