export enum PermissionsList {
    all = "*",
    accountCurrent = "account.current",
    accountCreate = "account.create",
    accountList = "account.list",
    accountDelete = "account.delete",
    accountUpdate = "account.update",
    attendanceScan = "attendance.scan",
    attendanceList = "attendance.list",
    attendanceDelete = "attendance.delete",
    attendanceClockIn = "attendance.clock_in",
    participantList = "participant.list",
    participantCreate = "participant.create",
    participantUpdate = "participant.update",
    participantDelete = "participant.delete",
    roomList = "room.list",
    scheduleList = "schedule.list",
    scheduleCreate = "schedule.create",
    scheduleUpdate = "schedule.update",
    wallList = "wall.list",
    workplaceList = "workplace.list",
}
