name: bitsenbytesPROD

services:
  bitsenbytesfrontendPROD:
    mem_limit: 512m
    memswap_limit: 512m
    image: 10.10.1.110:32000/managementplatform:bitsenbytesfrontendPROD_0.0.4
    container_name: bitsenbytesfrontendPROD
    build:
      context: .
      target: bitsenbytesfrontendPROD
    ports:
      - 8080:80

  bitsenbytesbackendPROD:
    mem_limit: 512m
    memswap_limit: 512m
    image: 10.10.1.110:32000/managementplatform:bitsenbytesbackendPROD_0.0.2_test_deployment_3
    container_name: bitsenbytesbackendPROD
    build:
      context: .
      target: bitsenbytesbackendPROD
    ports:
      - 3000:3000