name: bitsenbytesPROD

services:
  bitsenbytesfrontendPROD:
    mem_limit: 512m
    memswap_limit: 512m
    image: 10.10.1.110:32000/managementplatform:bitsenbytesfrontendPROD_${VERSION}
    container_name: bitsenbytesfrontendPROD
    build:
      context: .
      target: bitsenbytesfrontendPROD
    ports:
      - 8080:80