name: bitsenbytesACC

services:
  bitsenbytesfrontendACC:
    mem_limit: 512m
    memswap_limit: 512m
    image: 10.10.1.110:32000/managementplatform:bitsenbytesfrontendACC__0.0.4
    container_name: bitsenbytesfrontendACC
    build:
      context: .
      target: bitsenbytesfrontendACC
    ports:
      - 8080:80

  bitsenbytesbackendACC:
    mem_limit: 512m
    memswap_limit: 512m
    image: 10.10.1.110:32000/managementplatform:bitsenbytesbackendACC__0.0.4
    container_name: bitsenbytesbackendACC
    build:
      context: .
      target: bitsenbytesbackendACC
    ports:
      - 3000:3000