@startuml

entity Account {
    * id: number <<primary key>>
    * type: string
    * firstname: string
    * lastname: string
    * username: string
    * role: <<foreign key Permission.role>>
    * password: string
}

entity Participant {
    * id: number <<primary key>>
    * firstname: string
    * lastname: string
    * organisation: string
    * account: <<foreign key Account.id>>
    * rfid: string
    * createdAt: Date
    * active: boolean
    --
    clockedin: boolean
    financing: string
}

entity Attendance {
    * id: number <<primary key>>
    * participantID: number <<foreign key Participant.id>>
    * clockinDate: Date
    * signature: string
    --
    clockoutDate: Date
    workDuration: number
}

entity Permission {
    * id: number <<primary key>>
    * role: string
    * permissions: string
}

entity Room {
    * id: number <<primary key>>
    * name: string
    * width: number
    * height: number
    * scale: number
}

entity Wall {
    * id: number <<primary key>>
    * xpos: number
    * ypos: number
    * height: number
    * RoomID: number <<foreign key Room.id>>
}

entity Workplace {
    * id: number <<primary key>>
    * xpos: number
    * ypos: number
    * RoomID: number <<foreign key Room.id>>
    * name: string
    --
    extraInfo: blob
}

entity Schedule {
    * id: number <<primary key>>
    * name: string
    * startDate: Date
    --
    endDate: Date
}

entity ScheduleParticipant {
    * id: number <<primary key>>
    * scheduleId: number <<foreign key Schedule.id>>
    * participantId: number <<foreign key Participant.id>>
}

Account ||--|| Permission
Account ||--|| Participant
Participant ||--o{ Attendance
Participant ||--o{ ScheduleParticipant
Schedule ||--o{ ScheduleParticipant
Room ||--o{ Wall
Room ||--o{ Workplace
@enduml