@startuml database

entity Account {
    * id: number <<primary key>>
    * type: string
    * firstname: string
    * lastname: string
    * username: string
    * role: string <<foreign key Permission.role>>
    * password: string
}

entity Participant {
    * id: number <<primary key>>
    * firstname: string
    * lastname: string
    * organisation: string
    * account: number <<foreign key Account.id>>
    * rfid: string
    * createdAt: Date
    * active: boolean
    --
    clockedin: boolean
    financing: string
}

entity Attendance {
    * id: number <<primary key>>
    * participantID: number <<foreign key Participant.id>>
    * clockinDate: Date
    * signature: string
    --
    clockoutDate: Date
    workDuration: number
}

entity Permission {
    * id: number <<primary key>>
    * role: string
    * permissions: string
}

entity ApiKey {
    * id: number <<primary key>>
    * apikey: string
    * permissionId: number <<foreign key Permission.id>>
}

entity Room {
    * id: number <<primary key>>
    * name: string
    * width: number
    * height: number
    * scale: number
    --
    rotation: number
}

entity Wall {
    * id: number <<primary key>>
    * xpos: number
    * ypos: number
    * height: number
    * RoomID: number <<foreign key Room.id>>
    --
    rotation: number
}

entity Workplace {
    * id: number <<primary key>>
    * xpos: number
    * ypos: number
    * RoomID: number <<foreign key Room.id>>
    * name: string
    --
    extraInfo: string
    rotation: number
}

entity Schedule {
    * id: number <<primary key>>
    * name: string
    * startDate: Date
    * participant: number <<foreign key Participant.id>>
    --
    endDate: Date
    monMorning: number <<foreign key Workplace.id>>
    monEvening: number <<foreign key Workplace.id>>
    thuesMorning: number <<foreign key Workplace.id>>
    thuesEvening: number <<foreign key Workplace.id>>
    wedMorning: number <<foreign key Workplace.id>>
    wedEvening: number <<foreign key Workplace.id>>
    thursMorning: number <<foreign key Workplace.id>>
    thursEvening: number <<foreign key Workplace.id>>
    friMorning: number <<foreign key Workplace.id>>
    friEvening: number <<foreign key Workplace.id>>
}

Permission ||--o{ Account
Permission ||--o{ ApiKey
Account ||--o{ Participant
Participant ||--o{ Attendance
Participant ||--o{ Schedule : participant
Room ||--o{ Wall
Room ||--o{ Workplace
Workplace |o--o{ Schedule : monMorning
Workplace |o--o{ Schedule : monEvening
Workplace |o--o{ Schedule : thuesMorning
Workplace |o--o{ Schedule : thuesEvening
Workplace |o--o{ Schedule : wedMorning
Workplace |o--o{ Schedule : wedEvening
Workplace |o--o{ Schedule : thursMorning
Workplace |o--o{ Schedule : thursEvening
Workplace |o--o{ Schedule : friMorning
Workplace |o--o{ Schedule : friEvening
@enduml
